---
- name: Quay Management
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Manage telescope Quay Organization"
      ansible.builtin.include_role:
        name: infra-ansible/roles/scm/quay
